spring.datasource.url=jdbc:mysql://localhost:3306/esquadria
spring.datasource.username=root
spring.datasource.password=riacho123

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update

spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

spring.jpa.show-sql=true
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

app.upload.dir=C:/riacho-uploads/produtos

server.port=8080
//Podemos criar diferentes profiles para desenvolvimento ou producao, esse seria o principal e so avisariamos o spring qual ambiente usa
//Ex: spring.profiles.active=dv ou spring.profiles.active=prod 