# Configuracao do datasource (persistencia em arquivo)
spring.datasource.url=jdbc:h2:file:./data/testdb;DB_CLOSE_DELAY=-1
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Hibernate criar ou atualizar as tabelas com base nas suas entidades
spring.jpa.hibernate.ddl-auto=update

# Habilitar o console do H2
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

server.port=8080

spring.jpa.show-sql=true
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

//Podemos criar diferentes profiles para desenvolvimento ou producao, esse seria o principal e so avisariamos o spring qual ambiente usar
//Ex: spring.profiles.active=dev ou spring.profiles.active=prod 